FROM alpine as builder
RUN apk add git
ADD https://api.github.com/repos/SGmuwa/Web-develop-frontend-7-semester/git/refs/heads/master version.json
RUN git clone -bmaster https://github.com/SGmuwa/Web-develop-frontend-7-semester.git
FROM nginx
COPY --from=builder /Web-develop-frontend-7-semester/dist /usr/share/nginx/html
