version: "3"
services:
  frontend:
    image: frontend
    build: ./frontend/


  #backend:
    #image: backend
    #build: ./backend


  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
