FROM openjdk:14-jdk-alpine
RUN apk add git maven
ADD https://api.github.com/repos/SGmuwa/Web-develop-backend-7-semester/git/refs/heads/master version.json
RUN git clone -bmaster https://github.com/SGmuwa/Web-develop-backend-7-semester.git
WORKDIR /Web-develop-backend-7-semester
RUN mvn package
WORKDIR /
RUN find . -iname "ItemService*.jar"
ARG JAR_FILE=/Web-develop-backend-7-semester/target/ItemService-1.0-SNAPSHOT.jar
RUN cp ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
