FROM openjdk:14-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=Web-develop-backend-7-semester/target/ItemService-1.0-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
